const local = 'http://127.0.0.1:8000/api';
export const loginAPI = `${local}/login`
export const RegisterAPI = `${local}/register`
export const PrepareAccountAPI = `${local}/account`
export const AllParentsCategoriesAPI = `${local}/category/parents`
export const ChildCategoriesOfParentAPI = `${local}/category/child/`
export const GetProfileInfo = `${local}/profile`
export const LogoutAPI = `${local}/logout`
export const ChangePasswordAPI = `${local}/password/change`
export const AddProjectAPI = `${local}/projects`